import React, { ReactElement } from "react";
import Head from "next/head";
import styles from "../../../pages/index.module.scss";
import { Footer } from "./Footer";
import { ExitButton } from ".";

interface Props {
  locale: string;
  children: JSX.Element | JSX.Element[];
}

export function Layout({ locale, children }: Props): ReactElement {
  return (
    <div>
      <Head>
        <title>Lou&You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div
            className="select is-rounded is-small"
            style={{
              position: "absolute",
              top: "110px",
              right: "30px",
            }}
          >
            <select defaultValue={locale}>
              <option value="en">EN</option>
              <option value="de">DE</option>
            </select>
          </div> */}

        {children}

        <ExitButton />
      </main>
    </div>
  );
}
