import React, { ReactElement } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import ExitButton from "./ExitButton";

interface Props {
  children: JSX.Element | JSX.Element[];
}

function Layout({ children }: Props): ReactElement {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lou&You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {children}

        {/* <ExitButton /> */}
      </main>

      <footer></footer>
    </div>
  );
}

export default Layout;
