import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import logo from "../public/logo.png";
import GetHelp from "../components/GetHelp";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Lou&You</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Image src={logo} width="210" height="120" alt="logo" />
                <section className="block">
                    <div className="block py-2">
                        <p>Hi, my name is Lou,</p>
                        <br />
                        <p>
                            I’m the first digital companion for people affected
                            by gender-based violence. Whatever you might go
                            through, I am here to support you on your journey
                            towards a self-determined life.
                            <br />
                            <br />
                            Tell me a little about what your situation and I’ll
                            show you what might be helpful for you.{" "}
                        </p>
                    </div>
                    <GetHelp />

                    <p className="block pt-5">
                        If you’d like to learn more about sexual or domestic
                        violence, you can find out more{" "}
                        <a href="#" className="is-primary">
                            here.
                        </a>
                    </p>
                    <p className="block">
                        You’d like to know more about me?
                        <br /> Let me <a>introduce myself to you.</a>
                        <br /> And if you’d like to stay in touch, sign up to my
                        newsletter <a>here</a>. One thing is for sure: together,{" "}
                        <a>we can change a lot.</a>
                    </p>
                </section>
            </main>

            <footer></footer>
        </div>
    );
};

export default Home;
