export enum COOKIES {
  COOKIES_POPUP_RESOLVED = "COOKIES_POPUP_RESOLVED",
  EXIT_BUTTON_POPUP = "EXIT_BUTTON_POPUP",
  HIDE_EXIT_BUTTON = "HIDE_EXIT_BUTTON",
  FONT_BIG = "FONT_BIG",
  DISABLE_COOKIES = "DISABLE_COOKIES",
  CONTRAST = "CONTRAST",
  ENABLE_ANALYTICS = "ENABLE_ANALYTICS",
  NEXT_LOCALE = "NEXT_LOCALE",
}

export const ALL_COOKIES: Omit<COOKIES, COOKIES.DISABLE_COOKIES>[] = [
  COOKIES.CONTRAST,
  COOKIES.EXIT_BUTTON_POPUP,
  COOKIES.HIDE_EXIT_BUTTON,
  COOKIES.FONT_BIG,
  COOKIES.CONTRAST,
  COOKIES.ENABLE_ANALYTICS,
  COOKIES.NEXT_LOCALE,
];
